sudo: false
language: node_js
node_js:
    - "5.1"
    - "6"
    - "stable"

install:
    - npm install eslint -g
    - npm install

script:
    - npm run lint
    - npm test
after_script:
    - npm run coveralls

notifications:
    email: false
